apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: golang-starter
  title: Golang
  description: Create a Golang repo with this template
  tags:
    - go
spec:
  type: service
  owner: engineering-services

  parameters:
    - title: Fill in template parameters
      required:
        - name
        - project_short_description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        project_short_description:
          title: Description
          type: string
          description: Description of the component
    - title: Choose owner and repo
      required:
        - access
      properties:
        access:
          title: Access
          type: string
          description: "Who should have access to the repo. If you wanna add a GitHub team, then remember to do it like: 'BESTSELLER/<group-name' eg. 'BESTSELLER/engineering-services'"

      

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./template
        values:
          name: '{{ parameters.name }}'
          project_short_description: '{{ parameters.project_short_description }}'

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: 'github.com?owner=BESTSELLER&repo={{parameters.name}}'
        access: '{{ parameters.access }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
